### PR TITLE
Fix crashing when writing C tables with -b 512

### PR DESCRIPTION
**Pull request by AlexGuo1998**
See https://github.com/Chia-Network/bladebit/issues/249#issuecomment-1313442568 for explanation

### CODE REVIEW

**Comment by harold-b** [comment]
Pasting the PR summary here from @AlexGuo1998 ( https://github.com/Chia-Network/bladebit/issues/249#issuecomment-1313442568):

After digging into the code I assume this is a bug.

https://github.com/Chia-Network/bladebit/blob/9fac46aff0476e829d476412de18497a3a2f7ed8/src/plotdisk/k32/CTableWriterBounded.h#L305-L306

https://github.com/Chia-Network/bladebit/blob/9fac46aff0476e829d476412de18497a3a2f7ed8/src/plotdisk/MapWriter.h#L192-L198

Length of `_mapBitCounts` should be `_numBuckets+ExtraBucket` i.e. `_numBuckets`, 512. However it's defined as:

https://github.com/Chia-Network/bladebit/blob/9fac46aff0476e829d476412de18497a3a2f7ed8/src/plotdisk/k32/CTableWriterBounded.h#L355-L358

https://github.com/Chia-Network/bladebit/blob/9fac46aff0476e829d476412de18497a3a2f7ed8/src/plotdisk/DiskPlotConfig.h#L4

Oops.

Anything more than 256 buckets would crash, because `uint32 _threadCount` get overridden to an arbitrary large number, making `jobs[i]` pointing to an invalid address.

https://github.com/Chia-Network/bladebit/blob/9fac46aff0476e829d476412de18497a3a2f7ed8/src/threading/MTJob.h#L530-L534

**Comment by harold-b** [comment]
I reviewed  it and you are correct, I appreciate the fix!
I am surprised that it had worked before in local runs with this bug present.

**Comment by harold-b** [comment]
It seems the commit was made from `master` instead of the latest `develop`. Can you please rebase your commit from the latest `develop` instead of `master` since this is supposed to be merged into develop, I need the history to remain linear. Then do a `push --force` so that

**Comment by AlexGuo1998** [comment]
done

**Pull request merged**
